logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns
    username: admin
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true
    hibernate:
      ddl-auto: create